# Site settings
title: Brandi L. Grissom, Journalist
email: grissom.brandi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Brandi L. Grissom, Journalist
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://brandilgrissom.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
